# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SRM_RCPP_SIGMA_Y_INV_WOODBURY_PHI_INV <- function(SIGMA_U_INV, NI) {
    .Call('_srm_SRM_RCPP_SIGMA_Y_INV_WOODBURY_PHI_INV', PACKAGE = 'srm', SIGMA_U_INV, NI)
}

SRM_RCPP_SIGMA_Y_INV_WOODBURY_TMAT <- function(A_inv, Z_ind, Phi_inv) {
    .Call('_srm_SRM_RCPP_SIGMA_Y_INV_WOODBURY_TMAT', PACKAGE = 'srm', A_inv, Z_ind, Phi_inv)
}

SRM_RCPP_SIGMA_Y_INV_WOODBURY_ZA <- function(Z_ind, A_inv, NZ) {
    .Call('_srm_SRM_RCPP_SIGMA_Y_INV_WOODBURY_ZA', PACKAGE = 'srm', Z_ind, A_inv, NZ)
}

SRM_RCPP_SIGMA_Y_INV_WOODBURY_Y_INV <- function(ZA, T_inv, A_inv) {
    .Call('_srm_SRM_RCPP_SIGMA_Y_INV_WOODBURY_Y_INV', PACKAGE = 'srm', ZA, T_inv, A_inv)
}

SRM_RCPP_COLSUMS <- function(x) {
    .Call('_srm_SRM_RCPP_COLSUMS', PACKAGE = 'srm', x)
}

SRM_RCPP_ROWSUMS <- function(x) {
    .Call('_srm_SRM_RCPP_ROWSUMS', PACKAGE = 'srm', x)
}

SRM_ARBSRM_TRACE_PRODUCT_MATRIX <- function(x, y) {
    .Call('_srm_SRM_ARBSRM_TRACE_PRODUCT_MATRIX', PACKAGE = 'srm', x, y)
}

SRM_ARBSRM_TRACE_PRODUCT_MATRIX_TRANSPOSE <- function(x, y) {
    .Call('_srm_SRM_ARBSRM_TRACE_PRODUCT_MATRIX_TRANSPOSE', PACKAGE = 'srm', x, y)
}

SRM_RCPP_SRM_ARBSRM_ONE_GROUP_ESTIMATE <- function(data, data_resp, bivariate) {
    .Call('_srm_SRM_RCPP_SRM_ARBSRM_ONE_GROUP_ESTIMATE', PACKAGE = 'srm', data, data_resp, bivariate)
}

SRM_RCPP_MATRIX_TRACE_PRODUCT <- function(x, y) {
    .Call('_srm_SRM_RCPP_MATRIX_TRACE_PRODUCT', PACKAGE = 'srm', x, y)
}

SRM_RCPP_SRM_MATRIX_MULT_LOGICAL <- function(x, y) {
    .Call('_srm_SRM_RCPP_SRM_MATRIX_MULT_LOGICAL', PACKAGE = 'srm', x, y)
}

SRM_RCPP_SRM_ARBSRM_SE_CREATE_CWU <- function(NF) {
    .Call('_srm_SRM_RCPP_SRM_ARBSRM_SE_CREATE_CWU', PACKAGE = 'srm', NF)
}

SRM_RCPP_SRM_COMPUTE_HESSIAN_RR <- function(hess_list, mu_y_der_list, mu_y_der_bool_list, SIGMA_Y_inv, npar) {
    .Call('_srm_SRM_RCPP_SRM_COMPUTE_HESSIAN_RR', PACKAGE = 'srm', hess_list, mu_y_der_list, mu_y_der_bool_list, SIGMA_Y_inv, npar)
}

SRM_RCPP_SRM_COMPUTE_LOG_LIKELIHOOD_GRADIENT_W0 <- function(sigma_y_inv, sigma_y_der, der_bool) {
    .Call('_srm_SRM_RCPP_SRM_COMPUTE_LOG_LIKELIHOOD_GRADIENT_W0', PACKAGE = 'srm', sigma_y_inv, sigma_y_der, der_bool)
}

SRM_RCPP_SRM_COMPUTE_LOG_LIKELIHOOD_GRADIENT_W1 <- function(sigma_y_inv, sigma_y_der) {
    .Call('_srm_SRM_RCPP_SRM_COMPUTE_LOG_LIKELIHOOD_GRADIENT_W1', PACKAGE = 'srm', sigma_y_inv, sigma_y_der)
}

SRM_RCPP_SRM_COMPUTE_LOG_LIKELIHOOD_GRADIENT_W2 <- function(sigma_y_inv, sigma_y_der, der_bool) {
    .Call('_srm_SRM_RCPP_SRM_COMPUTE_LOG_LIKELIHOOD_GRADIENT_W2', PACKAGE = 'srm', sigma_y_inv, sigma_y_der, der_bool)
}

SRM_RCPP_SRM_COMPUTE_NONZERO_GRADIENT_INDICES <- function(sigma_y_der, eps) {
    .Call('_srm_SRM_RCPP_SRM_COMPUTE_NONZERO_GRADIENT_INDICES', PACKAGE = 'srm', sigma_y_der, eps)
}

SRM_RCPP_SRM_DATA_LIST_CREATE_INSERTION_MATRIX <- function(x) {
    .Call('_srm_SRM_RCPP_SRM_DATA_LIST_CREATE_INSERTION_MATRIX', PACKAGE = 'srm', x)
}

SRM_RCPP_SRM_INSERT_ELEMENTS <- function(sigma_y0, Zis, sigma_u) {
    .Call('_srm_SRM_RCPP_SRM_INSERT_ELEMENTS', PACKAGE = 'srm', sigma_y0, Zis, sigma_u)
}

SRM_RCPP_ORDER <- function(x) {
    .Call('_srm_SRM_RCPP_ORDER', PACKAGE = 'srm', x)
}

SRM_RCPP_SRM_MAKE_DATA_MATRIX_PERSON_ONE_PERSON <- function(tmp_data3, no_person, no_vars, rr, person, pid) {
    .Call('_srm_SRM_RCPP_SRM_MAKE_DATA_MATRIX_PERSON_ONE_PERSON', PACKAGE = 'srm', tmp_data3, no_person, no_vars, rr, person, pid)
}

SRM_RCPP_SRM_MAKE_DATA_MATRIX_PERSON <- function(tmp_data3, no_person, no_vars, rr, persons) {
    .Call('_srm_SRM_RCPP_SRM_MAKE_DATA_MATRIX_PERSON', PACKAGE = 'srm', tmp_data3, no_person, no_vars, rr, persons)
}

SRM_RCPP_SRM_MAKE_DATA_MATRIX_DYAD_ONE_DYAD <- function(tmp_data3, no_vars, rr, dyad, did) {
    .Call('_srm_SRM_RCPP_SRM_MAKE_DATA_MATRIX_DYAD_ONE_DYAD', PACKAGE = 'srm', tmp_data3, no_vars, rr, dyad, did)
}

SRM_RCPP_SRM_MAKE_DATA_MATRIX_DYAD <- function(tmp_data3, no_vars, rr, no_dyads, dyads) {
    .Call('_srm_SRM_RCPP_SRM_MAKE_DATA_MATRIX_DYAD', PACKAGE = 'srm', tmp_data3, no_vars, rr, no_dyads, dyads)
}

SRM_RCPP_SRM_ULS_GRADIENT_SIGMA_PART <- function(cov_resid, SIGMA_Y_der, der_bool) {
    .Call('_srm_SRM_RCPP_SRM_ULS_GRADIENT_SIGMA_PART', PACKAGE = 'srm', cov_resid, SIGMA_Y_der, der_bool)
}

