# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SRM_RCPP_COLSUMS <- function(x) {
    .Call('_srm_SRM_RCPP_COLSUMS', PACKAGE = 'srm', x)
}

SRM_RCPP_ROWSUMS <- function(x) {
    .Call('_srm_SRM_RCPP_ROWSUMS', PACKAGE = 'srm', x)
}

SRM_ARBSRM_TRACE_PRODUCT_MATRIX <- function(x, y) {
    .Call('_srm_SRM_ARBSRM_TRACE_PRODUCT_MATRIX', PACKAGE = 'srm', x, y)
}

SRM_ARBSRM_TRACE_PRODUCT_MATRIX_TRANSPOSE <- function(x, y) {
    .Call('_srm_SRM_ARBSRM_TRACE_PRODUCT_MATRIX_TRANSPOSE', PACKAGE = 'srm', x, y)
}

SRM_RCPP_SRM_ARBSRM_ONE_GROUP_ESTIMATE <- function(data, data_resp, bivariate) {
    .Call('_srm_SRM_RCPP_SRM_ARBSRM_ONE_GROUP_ESTIMATE', PACKAGE = 'srm', data, data_resp, bivariate)
}

SRM_RCPP_MATRIX_TRACE_PRODUCT <- function(x, y) {
    .Call('_srm_SRM_RCPP_MATRIX_TRACE_PRODUCT', PACKAGE = 'srm', x, y)
}

SRM_RCPP_SRM_MATRIX_MULT_LOGICAL <- function(x, y) {
    .Call('_srm_SRM_RCPP_SRM_MATRIX_MULT_LOGICAL', PACKAGE = 'srm', x, y)
}

SRM_RCPP_SRM_ARBSRM_SE_CREATE_CWU <- function(NF) {
    .Call('_srm_SRM_RCPP_SRM_ARBSRM_SE_CREATE_CWU', PACKAGE = 'srm', NF)
}

SRM_RCPP_SRM_COMPUTE_HESSIAN_RR <- function(hess_list, mu_y_der_list, mu_y_der_bool_list, SIGMA_Y_inv, npar) {
    .Call('_srm_SRM_RCPP_SRM_COMPUTE_HESSIAN_RR', PACKAGE = 'srm', hess_list, mu_y_der_list, mu_y_der_bool_list, SIGMA_Y_inv, npar)
}

SRM_RCPP_SRM_COMPUTE_LOG_LIKELIHOOD_GRADIENT_W0 <- function(sigma_y_inv, sigma_y_der, der_bool) {
    .Call('_srm_SRM_RCPP_SRM_COMPUTE_LOG_LIKELIHOOD_GRADIENT_W0', PACKAGE = 'srm', sigma_y_inv, sigma_y_der, der_bool)
}

SRM_RCPP_SRM_COMPUTE_NONZERO_GRADIENT <- function(sigma_y_der, eps) {
    .Call('_srm_SRM_RCPP_SRM_COMPUTE_NONZERO_GRADIENT', PACKAGE = 'srm', sigma_y_der, eps)
}

SRM_RCPP_SRM_DATA_LIST_CREATE_INSERTION_MATRIX <- function(x) {
    .Call('_srm_SRM_RCPP_SRM_DATA_LIST_CREATE_INSERTION_MATRIX', PACKAGE = 'srm', x)
}

SRM_RCPP_SRM_INSERT_ELEMENTS <- function(sigma_y0, Zis, sigma_u) {
    .Call('_srm_SRM_RCPP_SRM_INSERT_ELEMENTS', PACKAGE = 'srm', sigma_y0, Zis, sigma_u)
}

SRM_RCPP_SRM_ULS_GRADIENT_SIGMA_PART <- function(cov_resid, SIGMA_Y_der, der_bool) {
    .Call('_srm_SRM_RCPP_SRM_ULS_GRADIENT_SIGMA_PART', PACKAGE = 'srm', cov_resid, SIGMA_Y_der, der_bool)
}

